### ISSUE TITLE
Parallelization breaks frame numbering in output

### ISSUE THREAD

**Issue by Wolfffff** [Wolfffff/bee-box#1]
[matching_pipeline.py](https://github.com/Wolfffff/bee-box/tree/main/analysis/aruco_tools)

When using the -p flag, frame numbers are only returned for a small portion of the data frame(likely a chunk) with others returned as 0.

**Comment by dyknapp** [comment]
Fixed!  This was a bug arising from insertion of rows for missing tags into the partial results matrices retrieved from the processes.  Specifically, in some cases, the program would mistake the first row containing frame numbers as being in place of a missing row and consequently add a row filled with zeros.
