### ISSUE TITLE
Rolling window tag-track association slows down as size grows

### ISSUE THREAD

**Issue by Wolfffff** [Wolfffff/bee-box#3]
It appears that as we pus our data into the hundreds of tens of frames, the performance of the rolling window tag-track association drops drastically.  This could be due to the growing size of tags and tracks as our frame count grows.

**Comment by dyknapp** [comment]
Fixed!  All completely-zero rows and columns are removed _prior_ to Hungarian matching.  Previously, Hungarian matching was being applied on the full cost matrix that had a ton of meaningless columns and rows, before meaningless data was filtered out afterwards.  With the new prior removal method, we also lost the need for the filtering afterwards.
